name = "9router"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[alias]
"@/lib/usageDb.js" = "./src/stubs/usageDb.js"

# Step 3: Paste your KV & D1 IDs here
[[kv_namespaces]]
binding = "KV"
id = "e00b29f4247e43d78d0f983330f34bad"

[[d1_databases]]
binding = "DB"
database_name = "proxy-db"
database_id = "a5243dff-120c-48fb-84bd-a34080ff6a50"
